name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Set Version Name
        id: set_version_name
        run: |
          VERSION_WITHOUT_V=$(echo '${{ github.ref_name }}' | sed 's/^v//')
          echo "version_name=${VERSION_WITHOUT_V}" >> $GITHUB_ENV

      - name: Build
        run: |
          go vet ./cmd/mm

          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${{ env.version_name }}'" -o ./releases/mm_linux_amd64 ./cmd/mm

          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${{ env.version_name }}'" -o ./releases/mm_linux_arm64 ./cmd/mm

          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${{ env.version_name }}'" -o ./releases/mm_darwin_amd64 ./cmd/mm

          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${{ env.version_name }}'" -o ./releases/mm_darwin_arm64 ./cmd/mm

          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${{ env.version_name }}'" -o ./releases/mm_windows_amd64.exe ./cmd/mm

      - name: Get History
        id: get_history
        run: |
          chmod +x history.sh
          output=$(./history.sh)
          echo "$output" > history.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: history.md

      - name: Upload Release Asset linux_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/mm_linux_amd64
          asset_name: mm_linux_amd64-${{ env.version_name }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset linux_arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/mm_linux_arm64
          asset_name: mm_linux_arm64-${{ env.version_name }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset darwin_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/mm_darwin_amd64
          asset_name: mm_darwin_amd64-${{ env.version_name }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset darwin_arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/mm_darwin_arm64
          asset_name: mm_darwin_arm64-${{ env.version_name }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset windows_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/mm_windows_amd64.exe
          asset_name: mm_windows_amd64-${{ env.version_name }}.exe
          asset_content_type: application/octet-stream